--> HTTPSConnectionPool(host='finfo.usthb.dz', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0c28174790>, 'Connection to finfo.usthb.dz timed out. (connect timeout=5)'))
==> at:2023-09-29 21:15:35.358104
